name: deploying a billion dollar unicorn to the moon (movieqart) 🚀🚀
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - uses: actions/setup-node@master
    #if using vue or npm specific packages
    # - name: Installing project dependencies
    #   run: npm install
    # - name: Building the project
    #   run: npm run production
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.production.example', '.env');"
    - name: Install Dependencies
      run: composer update --ignore-platform-reqs
    - name: Create zipped vendor directory
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./vendor.zip ./vendor
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: 📂 Sync files
      uses: wangyucode/sftp-upload-action@v1.3.2
      with:
        host: ${{ secrets.MOVIEQART_PRODUCTION_SITE_SERVER }}
        port: 21098
        username: ${{ secrets.MOVIEQART_PRODUCTION_SITE_USER }}
        password:  ${{ secrets.MOVIEQART_PRODUCTION_SITE_PASSWORD }}
        localDir: '/'
        remoteDir: ${{ secrets.MOVIEQART_PRODUCTION_SITE_SERVER_DIR }}
        dryRun: false # use dryRun for test
