name: deploying a billion dollar unicorn to the moon (movieqart) 🚀🚀
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - uses: actions/setup-node@master
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run production
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.production.example', '.env');"
    - name: Install Dependencies
      run: composer update --ignore-platform-reqs
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.MOVIEQART_PRODUCTION_SITE_SERVER }}
        username: ${{ secrets.MOVIEQART_PRODUCTION_SITE_USER }}
        password: ${{ secrets.MOVIEQART_PRODUCTION_SITE_PASSWORD }}
        port: 21
        protocol: ftp
        server-dir: ${{ secrets.MOVIEQART_PRODUCTION_SITE_SERVER_DIR }}
