name: deploying a billion dollar unicorn to the moon (movieqart) 🚀🚀
on:
  push:
    branches:
      - staging
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
    - uses: actions/setup-node@master
    - name: Installing project dependencies
      run: npm install
    - name: Building the project
      run: npm run production
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer update --ignore-platform-reqs
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: 📂 Sync files
      uses: wangyucode/sftp-upload-action@v1.3.2
      with:
        host: ${{ secrets.MOVIEQART_PRODUCTION_SITE_SERVER }}
        port: 21098
        username: ${{ secrets.MOVIEQART_PRODUCTION_SITE_USER }}
        password:  ${{ secrets.MOVIEQART_PRODUCTION_SITE_PASSWORD }}
        localDir: '/'
        remoteDir: ${{ secrets.MOVIEQART_STAGING_SITE_SERVER_DIR }}
        dryRun: false
